// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planora.Todo.Infrastructure.Persistence;

#nullable disable

namespace Planora.Todo.Infrastructure.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260511105105_AddViewerCompletion")]
    partial class AddViewerCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("todo")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Hidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int?>("RequiredWorkers")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Todo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsDeleted");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "Status", "IsDeleted", "CreatedAt")
                        .HasDatabaseName("ix_todo_items_user_status_deleted_created");

                    b.ToTable("TodoItems", "todo");
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemId", "CreatedAt");

                    b.ToTable("todo_item_comments", "todo");
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItemShare", b =>
                {
                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("uuid");

                    b.HasKey("TodoItemId", "SharedWithUserId");

                    b.HasIndex("SharedWithUserId");

                    b.ToTable("todo_item_shares", "todo");
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItemWorker", b =>
                {
                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TodoItemId", "UserId");

                    b.HasIndex("TodoItemId");

                    b.HasIndex("UserId");

                    b.ToTable("todo_item_workers", "todo");
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.UserTodoViewPreference", b =>
                {
                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CompletedByViewer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedByViewerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HiddenByViewer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ViewerCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ViewerId", "TodoItemId");

                    b.HasIndex("TodoItemId", "ViewerId");

                    b.ToTable("user_todo_view_preferences", "todo");
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.OwnsMany("Planora.Todo.Domain.Entities.TodoItemTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("TodoItemId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TodoItemId");

                            b1.ToTable("todo_tags", "todo");

                            b1.WithOwner()
                                .HasForeignKey("TodoItemId");
                        });

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItemComment", b =>
                {
                    b.HasOne("Planora.Todo.Domain.Entities.TodoItem", null)
                        .WithMany()
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItemShare", b =>
                {
                    b.HasOne("Planora.Todo.Domain.Entities.TodoItem", null)
                        .WithMany("SharedWith")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItemWorker", b =>
                {
                    b.HasOne("Planora.Todo.Domain.Entities.TodoItem", null)
                        .WithMany("Workers")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Planora.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.Navigation("SharedWith");

                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
